### ISSUE TITLE
Can't get handlers.getUser

### ISSUE THREAD

**Issue by nimbusNuii** [juandevelop85/hapi-socket.io#3]
method: 'GET',
    path: '/user/getUser',
    config: {
        auth: false,
        handler: handlers.getUser,
        description: 'Example description',
        notes: 'Example notes',
        plugins: {
            'hapi-swagger': {
                payloadType: 'form'
            },
            'hapi-socket.io': {
                event: 'getUser',
                emit: handlers.emitUser
            }
        },
        tags: ['api'],
        validate: {
            query: {
                idUser: Joi.string().required()
            },
            headers: Joi.object({
                'authorization': Joi.string().required()
            }).unknown()
        }
    }

**Comment by juandevelop85** [comment]
Hi handlers.getUser its an example, handlers is the name of the file that contains the function getUser.

thanks
